name: docker deployment
on: workflow_dispatch
jobs: 
  build:
    runs_on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4.2.2
      - name: docker image build
        run: docker build -t ${{vars.DOCKER_USERNAME}}/food-app .
      - name: Docker Login
        uses: docker/login-action@v3.4.0
        with:
          username: ${{vars.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
      - name: push image to docker hub
        run: docker push ${{vars.DOCKER_USERNAME}}/food-app
